[server]
maxUploadSize=3000
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
enableStaticServing = true

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "info"